In [ ]:
Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [ ]:
ANS-Yes, there is a difference in the data type of the variables list_ and array_list.

To print the data types of both variables, you can use the type() function in Python. Here's the code to do that:

python
Copy code
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))
When you run this code, it will output something like:

OUTPUT
Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>

In [ ]:
Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

ANS-To print the data type of each element in both list_ and array_list, you can use a loop to iterate through each element and then use the type() function to determine the data type. Here's the code:

In [ ]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Data type of each element in list_
print("Data type of each element in list_:")
for item in list_:
    print(type(item))

# Data type of each element in array_list
print("\nData type of each element in array_list:")
for item in array_list:
    print(type(item))


In [ ]:
OUTPUT

Data type of each element in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of each element in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [ ]:
Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

ANS-Yes, there will be a difference in the data type of the elements present in list_ and array_list. When you create array_list with the dtype=int, the elements will be explicitly converted to integers.

Let's see the updated code and print the data types of each element in both list_ and array_list:

In [ ]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Data type of each element in list_
print("Data type of each element in list_:")
for item in list_:
    print(type(item))

# Data type of each element in array_list
print("\nData type of each element in array_list:")
for item in array_list:
    print(type(item))


In [ ]:
OUTPUT

Data type of each element in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of each element in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [ ]:
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)


Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [ ]:
ANS- import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# (i) Shape of num_array
shape = num_array.shape
print("(i) Shape of num_array:", shape)

# (ii) Size of num_array
size = num_array.size
print("(ii) Size of num_array:", size)


In [ ]:
OUTPUT

(i) Shape of num_array: (2, 3)
(ii) Size of num_array: 6


In [ ]:
Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

ANS-You can create a 3x3 NumPy array filled with zeros using the np.zeros() function. Here's the code to do that:

In [ ]:
import numpy as np

# Creating a 3x3 matrix of zeros
zero_matrix = np.zeros((3, 3))

print(zero_matrix)


In [ ]:
OUTPUT

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

ANS-You can create an identity matrix of shape (5, 5) using the np.identity() function from NumPy. Here's the code to do that:

In [ ]:
import numpy as np

# Creating a 5x5 identity matrix
identity_matrix = np.identity(5)

print(identity_matrix)


In [ ]:
OUTPUT

(i) Shape of num_array: (2, 3)
(ii) Size of num_array: 6
